const wallets =
[
    {
        name:'boyka',
        Coins: [{
            name:'USDT',
            networks:[
                {
                name:'Tron TRC-20',
                address:""
                },
                {
                name:'Ethereum ERC-20',
                address:''
                },
                {
                name:'BEB-20',
                address:'',
                }
            ]},
            {
                name:'Bitcoin',
                networks:[
                {
                name:'Bitcoin',
                address:''
                }
                ]
            },
            {
                name:'Ethereum',
                networks:[
                    {
                        name:'ERC-20',
                        address:''
                    },
                    {
                        name:'BEP-20',
                        address:''
                    }
                ]
            },
            {
                name:'LiteCoin',
                networks:[
                    {
                        name:'Litcoin',
                        address:''
                    }
                ]
            },
            {
                name:'BnB',
                networks:[
                    {
                        name:'ERC-20',
                        address:''
                    },
                    {
                        name:'BEP-20',
                        address:''
                    }
                ]
            },
            {
                name:'Tron',
                networks:[
                    {
                        name:'Tron TRC-20',
                        address:""
                    },
                    {
                        name:'BEP-20',
                        address:''
                    }
                ]
            },
            {
                name:'Xrp',
                networks:[
                    {
                    name:'Ripple',
                    address:""
                    }
                ]
            },
            {
                name:'Bitcoin Cash',
                networks:[
                    {
                        name:'Ethereum ERC-20',
                        address:''
                    },
                    {
                        name:'BEP-20',
                        address:''
                    }
                ]
            },
            {
                name:'Dash',
                networks:[
                    {
                        name:'Dash',
                        addrss:''
                    }
                ]
            },
            {
                name:'Gala',
                networks:[
                    {
                        name:'Ethereum ERC-20',
                        address:""
                    }
                ]
            },
            {
                name:'DogeCoin',
                networks:[
                    {
                        name:'DogeCoin',
                        address:''
                    }
                ]
            },
            {
            name:'Matic',
            networks:[
                {
                    name:'Polygon',
                    address:''
                },
                {
                    name:'Ethereum',
                    address:''
                },
                {
                    name:'BEP-20',
                    address:''
                }
            ]
            },
            {
                name:'USDC',
                networks:[
                    {
                        name:'Polygon',
                        address:""
                    },
                    {
                        name:'Ethereum ERC-20',
                        address:''
                    },
                    {
                        name:'BEP-20',
                        address:''
                    }
                ]
            },
            {
                name:'Mana',
                networks:[
                    {
                        name:'Ethereum ERC-20',
                        address:''
                    },
                    {
                        name:'BEP-20',
                        address:''
                    }
                ]
            },
            {
                name:'SUSHI',
                networks:[
                    {
                        name:'Ethereum ERC-20',
                        address:''
                    },
                    {
                        name:'BEP-20',
                        address:''
                    }
                ]
            }
        ]
    },
    
]